### ISSUE TITLE
Where is the feature double click for hide portals. Did you delete it ?

### ISSUE THREAD

**Issue by user4855anomalie** [Ross-Patterson/Portals-Desktop-Organization#119]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ross-Patterson** [comment]
I replaced it with CTRL+SHIFT+A option to show/hide portals, because double click on the desktop had a problem where when the portals were made visible, you had to triple click the desktop which was just fiddly and annoying. Thoughts? Was double click better even with that annoyance?

![image](https://user-images.githubusercontent.com/66630787/233686819-ba0ef08d-383d-487f-b67f-9f62172a65ac.png)

**Comment by jerrrb** [comment]
i think that double (or triple lol) click was much better even with his issues. Maybe you can put both options?
PS: love ur app

**Comment by Ross-Patterson** [comment]
Its back in the beta channel, switch to it in the settings to get v3.0.1.0:
![image](https://user-images.githubusercontent.com/66630787/234682224-e98c8a14-7d87-4d79-b819-5a632df6b09a.png)

**Comment by Ross-Patterson** [comment]
3.0.1.0 is now released to prod channel, so closing this issue
