### ISSUE TITLE
Hiding / Showing Animation

### ISSUE THREAD

**Issue by miroslawWasylik** [Ross-Patterson/Portals-Desktop-Organization#12]
Hi again,

Thanks for autofocus show/hide feature. And again I have an idea.

Maybe will be great when on showing or hiding panel will be animation when panels are showing down or up. In JavaScript this is an "ease" parameter in transition - most linear.

I mean for example when I put my cursor on titlebar - panels is showing, but it is super fast on/off. But maybe great idea is add animation on that function.

 Check this out!

**Comment by Ross-Patterson** [comment]
This is something I am looking into, it is quite difficult to achieve in XAML/.NET because the TO and FROM values are changing depending on the width/height of the Portals. XAML can't animate between values that are set via Bindings, so I need to do it in code behind.

I will keep doing my research and I will figure out a way.
