### ISSUE TITLE
BUGs (after purchase)

### ISSUE THREAD

**Issue by gittmin** [Ross-Patterson/Portals-Desktop-Organization#154]
SYSTEM: WINDOWS 11 22H2 BUGS

BUG LIST

1. Missing the ability to change the default location for all root folders so that it doesn't make the desktop messy? I don't want to hide my desktop because I still use it for other things.

2. Can not drag new shortcuts created into a portal from dragging from the startmenu. Would just use the regular desktop for shortcut creation from the start menu but it becomes cluttery as hard to manage as every portal duplicated or rooted on the desktop. And hiding the desktop makes it annoying when you need the desktop visible for creating shortcuts via the START menu.

3.When changing the root folder via the settings, there is not way to copy and paste an entire path into the "Browse Folder" window as it uses the slower interface where one has to manually go through many folders to locate the spot. This can be tiring if you have many portals. I would suggest using the newer version that most use where

**Comment by Ross-Patterson** [comment]
Hi,

1. Not sure exactly what you mean here, there are 3 ways to create Portals:
    > Clicking the "New Portal" button from the main window and selecting an existing folder (from anywhere)
    > Clicking the "New Portal" button from the main window and creating a new folder (anywhere), then selecting it.
    > Right click on any folder (anywhere) > Create Portal from Folder
    > Right click desktop background > New Portal and Folder - this is the only one that defaults the new folder to the desktop.
    
2.  Good observation, I assume this is what you see:
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/1ad58945-635f-47c5-b92e-6b74df4e8c01)

Will take a look.

3. Yep the folder picker annoys me also but unfortunately the framework I am using does not allow for the more modern folder picker without using a custom library and I don't want the app to become too bloaty with custom libraries.

**Comment by dking02** [comment]
**ITEM 1**. The problem of new portal folders being created on the desktop (reported here and in item 1 of  issue 153) may be due to the setting for “Default Folder Picker Folder” in Setup > Customize > App Settings. 

The setting “C:\Users\username\Desktop” provided as part of installation places new portal folders generated by “New Portal and Folder” (context menu) or “Add Portal” button (Setups > Home using default location for new folder) directly on the desktop. If the setting has not been changed, I recommend creating a new folder on the desktop named “Portals” and changing the picker folder setting to “C:\Users\username\Desktop\Portals”. This will provide a common location for portal folders in a readily accessible folder. (Note: The folder can be located somewhere else if desired. Also note that the desktop folder can be relocated to another drive or folder and may not be in the usual location shown above.)

If you have invested a lot of effort customizing individual portals in the current layout, it is possible to move the portal folder to a new location with Explorer and then reconnect the existing portal to the folder in its new location from within Portals to preserve the customization. Otherwise, you can close the portal, move its folder from the desktop with Explorer, and then right-click on the folder to “Create portal from folder” from scratch in its new location. Before doing anything, save the current layout in the event of a problem.

**ITEM 2**. The new start menu in Windows 11 appears to have protection against unintentional removal of program shortcuts that actually worked in this case. When you drag a program shortcut item from the start menu to the desktop, Windows 11 will copy the program link to the user’s desktop folder. However, when an item is dragged-and-dropped from (or to) a portal, the action is performed as a move. Therefore, I suspect that dragging the program shortcut from the start menu is being rejected because moving (rather than copying) the program shortcut to the portal would result in the program becoming inaccessible from the start menu. It is still possible to bypass this protection via the More option in the start menu which provides direct access to the program shortcut in its start menu folder location.
