### ISSUE TITLE
`Win`+`D` minimizes all portals

### ISSUE THREAD

**Issue by Darthagnon** [Ross-Patterson/Portals-Desktop-Organization#19]
**Describe the bug**
Despite the changelog for v2.1.0.3 listing `> Portals will no longer minimize when Win+D is pressed (Show Desktop)`, `Win`+`D` minimizes all portals. It may have something to do with Win10's multiple desktops feature? When I had another desktop open, `Win`+`D` makes them all disappear on Desktop 1, but appear on Desktop 2.

**Expected behavior**
Would be nice to have "Double Click on the desktop to show/hide all portals", similar to how Fences does it. I've also often wished the context menu on a portal would give an option to open the management UI.

**Desktop (please complete the following information):**
 - OS: Win10 v1709
 - Browser: Ungoogled Chromium
 - Version: Portals v2.1.0.4

**Comment by Darthagnon** [comment]
Duplicate of #5

**Comment by Ross-Patterson** [comment]
#5 already covers this as you say, I am aware of the problem. Actually, windows doesn't really allow other applications to stay open when Win+D is pressed, its called "Show Desktop" and Microsoft try hard to ensure this is exactly what happens.

My solution in v2.1.0.3 was to make the portals children of the Desktop window, but this is still not 100% robust as you have seen. The reason is that the Desktop window seems to move about and is not always in the same place in the window hierarchy.

I have improved it in my current dev version to scan the hierarchy and find the desktop window by name then make the Portals children of it, but it still will not be 100% robust as any application can make a window with the same name as the desktop which could muck things up.
