### ISSUE TITLE
"Show Desktop" button hides portals

### ISSUE THREAD

**Issue by TBat** [Ross-Patterson/Portals-Desktop-Organization#213]
**To Reproduce**
1. Click the "show desktop" button in the taskbar (or hit windows key+D)
2. All portals minimize/disappear like every other application

**Expected behavior**
Portals should remain visible on the desktop while every other application minimizes

**Desktop**
 - OS: Windows 10
 - Browser: Brave
 - Version 3.1.0.2

**Comment by Ross-Patterson** [comment]
It should work, and does work in the majority of cases. In order to help debug why this isn't working on your machine I would need you to to install Spy++ and figure out which window is your Desktop and what the name of that window is.

If you are willing to do this let me know.

Portals is set up to expect "Progman" with a child of "SHELDLL_DefView", like so:

![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/40a2a4c4-0fb6-466f-a43d-1664fce08e71)

If yours is not like this for any reason then that might be the reason.

**Comment by Ross-Patterson** [comment]
Closing due to no response
