### ISSUE TITLE
Portal Icons persistent sorting criteria

### ISSUE THREAD

**Issue by Miquel-agp** [Ross-Patterson/Portals-Desktop-Organization#236]
Good evening, I am not sure if it is an intentional feature of the program, or if I just don't know how to do it correctly, but I really miss that when I set a sorting order for the icons on a portal, for example by descending modification date, it does not get saved and I have to set it every time I restart my computer.
Thank you very much.

**Comment by Ross-Patterson** [comment]
Hi Miquel, chosen sort order should be getting saved. I will see if I can replicate on my side.

**Comment by MIBGRUP** [comment]
Hello, thank you very much in advance.
It's very strange because the portals don't save the sorting for me.
Specifically, in the one I use the most, it points to a directory where there are only shortcuts inside. I like to sort them by creation date, but every time I launch portals, it resets to alphabetical order.

Thanks!

**Comment by Ross-Patterson** [comment]
This is fixed in the latest release.

**Comment by MIBGRUP** [comment]
Nice! Ross, now looks perfect.
