### ISSUE TITLE
Startup Scaling Issue

### ISSUE THREAD

**Issue by Qhronoboros** [Ross-Patterson/Portals-Desktop-Organization#253]
**Describe the bug**
At startup, the portals move to a different location than from the previous save point on a secondary monitor. This problem occurs when the monitors have different scaling in the Windows display settings.

**Additional context**
The portals are on my secondary monitor (1080p), which has a scaling of 100% in the Windows display setting. My primary monitor (1440p) has a scaling of 125%.

I did some testing and from my observations, this is the hypothesis I came up with.
The moment the program starts up, the portals get scaled to 125% because of the primary monitor, and then the portals get moved to their new location using the values of the previous save point, which in reality is not correct because of the scaling that was mentioned earlier.

Is there a way to make each portal remember its scaling or which specific monitor it was on?

**Screenshots of my testing**

Should also mention I have a third monitor that is vertical on the left, not that it matters much in this situation.

![afbeelding](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/47349395/92f4da6b-7a77-4d19-9090-37f95582931a)
So at the start, I have the portal on the primary monitor which is on a scale 125%.

![afbeelding](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/47349395/2844a04d-f76f-4fea-a7f2-26f8f8cf68bb)
I then move the portal vertically by inputting a new number -750. The portal is still suck in the primary monitor's 125% scaling.

![afbeelding](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/47349395/9e7d7343-a3e4-4095-ad59-302208f0d43c)
Changing that value to -751 updates the portal's scaling to the secondary monitor's scaling (100%)

![afbeelding](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/47349395/7371550f-1429-4be4-9196-3ba9e0757b5b)
Putting the value back to -750 puts it in its expected position from image 2.

Something else I also found. When you load a save point with this issue. There is a chance the save gets overwritten with new values for some reason.

**Desktop:**
 - OS: Windows 10
 - Portals Desktop Organization: Version 3.2.1.0

**Comment by Ross-Patterson** [comment]
Yes this issue I know about - but it is a real complex nightmare to figure out how to handle it properly.

I have a test build that I hope resolved the problem, would you be willing to test it out?

**Comment by Ross-Patterson** [comment]
Ok,
Please take a backup of: C:\Users\username\AppData\Local\Portals
So that you will not lose anything.
Then clear out: C:\Users\username\AppData\Local\Portals (you can leave the license.ptl file)

You can download the test version here:
https://downloads.portals-app.com/build-previews%2Fv3.3.0.0_b1%2Fportals_installer_v3-3-0-0_test1.exe?alt=media

Please test with multiple monitors with different scaling values and let me know how it goes!

**Comment by Qhronoboros** [comment]
I tried out the test version and it fixes the issue pretty well, the portals don't move to different locations when restarting the application and computer. The save points/layouts also don't get overwritten like in the 3.2.1.0 version.

I do have to mention that by re-doing the steps that I did in the screenshots on my first post. I get the same result, not that it matters much since the main issue has been fixed and it shouldn't bother anyone when they already have their portal windows set up.

**Comment by Ross-Patterson** [comment]
Nice, so the remaining issue is when you type a value in that ends up on a different monitor.

This is difficult - because if it was done "properly", then you would type in -750, but the -750 is as per your 125% scaled monitor, so when it lands on the 100% scaled monitor, the value would change to the position value according to 100% scaling (so -750 would change to -900 or something). This would massively confuse people, as to why values are randomly changing.

The coordinate system is not consistent across monitors, it depends on each monitors scaling :(
