### ISSUE TITLE
BUG: Show Desktop ( win+D ) some portals disappear

### ISSUE THREAD

**Issue by jupretz** [Ross-Patterson/Portals-Desktop-Organization#326]
### Check the Help Site and GitHub Issues/Discussions

- [x] I have checked and found nothing.

### Version

3.3.0.9

### Operating System

Windows 11

### What happened?

I enable the option to hide portals on double click, when i hide the portals and click Show desktop or Win+D from another application and then double click to show the hidden portals it's not showing all the portal, 1 of the portals remain hidden, even if my mouse hover to the area. 

I read there is someone with same problem with mine but his problem solved on it's own. [Here](https://github.com/Ross-Patterson/Portals-Desktop-Organization/issues/313) 

Here is the screenshot of WindowDetective
![Screenshot 2024-06-29 205001](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/37231313/111fd877-28e9-4c9e-a5f5-8f5650b3db9a)

And here is the screenrecord of what's happening. 

https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/37231313/88fbb5c7-6e61-42c5-a479-d4762b8508b4

### Steps to Reproduce

1. Hide the portals ( in my case i enable the option to double click to hide/show )
2. Open some application
3. Click Show Desktop or Win+D 
4. Show hidden portals

### What would you expect to happen?

Portals to not hide.

**Comment by Ross-Patterson** [comment]
The problem is explained here:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/issues/101#issuecomment-1523977037

The workaround is also given in the link above. Its not something I can fix I don't think, it seems to be a problem with windows itself. Workaround is essentially to create a dummy hidden portal window and make it bottom of the stack, then that one will be the one affected, but its always hidden anyway so it doesnt matter.
