### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by ongart-a** [Ross-Patterson/Portals-Desktop-Organization#6]
Portals is awesome. I would like to request some features. 

- Add Cut option when right clicking on a file in a portal 
- When deleting multiple files from portal, now the Windows delete confirmation box would show up for for each individual file. It should be that only one confirmation be shown for all the files deletion. 

Thank you very much. Keep up the good work.

Ongart

**Comment by Ross-Patterson** [comment]
@ongart-a , thanks for the feedback! Here are my thoughts/comments on your suggestions:

1. Cut - this is actually really painful to implement. As you have to communicate between applications to tell the other application the cut has succeeded and vice-versa, my app would have to listen for the cut being succeeded from other apps (i don't even know if this is possible). I attempted this in the past and the effort to make this happen to just too much for the benefit it gives. I could do cut and paste between Portals but this would cause a while lot of confusion because people would assume it would work between apps as well.

2. This is a good point - I will definitely look into fixing this. (I think the default in Windows 10 is to have no delete popup, so I missed this while testing).

**Comment by Ross-Patterson** [comment]
Item 2 is now available in v2.1.0.4.
