### ISSUE TITLE
Feature Request: Ability to copy paste url's to folder location field

### ISSUE THREAD

**Issue by Savasdotexe** [Ross-Patterson/Portals-Desktop-Organization#93]
**Is your feature request related to a problem? Please describe.**
I tried to copy paste the address of where I'd like the portal folder to be, because going to it via the folder picker is really time consuming and complicated, especially if it's buried somewhere within many folders.

**Describe the solution you'd like**
Simple, allow the ability to paste in the address field.

**Describe alternatives you've considered**
Other than to manually go through the folders or use the context menu one level up, but if you're like me who doesn't like a bloated context menu, the only option left is the first one after you remove the context menu addition.

**Additional context**
Maybe get rid of the top part on the main screen and have one button that opens a box/dialog and asks the user to input name, location and maybe options to customize at that point.

**Comment by Ross-Patterson** [comment]
Hi There,
I have changed the folder picker in v3.0.0.0 which I have made available for early access here:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/discussions/107

The folder picker is now the normal windows one (rather than Material one), so you can paste the address in.

Thanks!
